### ISSUE TITLE
Cannot find module 'mutag'

### ISSUE THREAD

**Issue by PragmaticEd** [chunqiuyiyu/mutag#1]
Test project started with commands:
```bash
npm init
npm install mutag --save
```

package.json
```json
{                                                             
  "name": "test",                                             
  "version": "1.0.0",                                         
  "description": "",                                          
  "main": "index.js",                                         
  "scripts": {                                                
    "test": "echo \"Error: no test specified\" && exit 1"     
  },                                                          
  "author": "",                                               
  "license": "ISC",                                           
  "dependencies": {                                           
    "mutag": "^2.0.5"                                         
  }                                                           
}                                                             
```

index.js
```js
const mutag = require('mutag');
```

Running `node index.js` returns:
```
module.js:328
    throw err;
    ^

Error: Cannot find module 'mutag'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/mnt/c/Users/PragmaticEd/Google Drive/music/editor/test/index.js:1:77)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
```

```
>> node -v
v4.2.6

>> npm -v
3.5.2
```

**Comment by chunqiuyiyu** [comment]
@PragmaticEd Thanks for your response, I have fixed the bug in v2.0.7.
